export const CONSTANTS = {
    API_KEY : 'b94da879216938c07bc512e903464e1a',
    API_ID : '1bab02c0',
    API_URL : 'https://api.edamam.com/api/food-database/v2/parser',
    LUNDI : 'Lundi',
    MARDI : 'Mardi',
    MERCREDI : 'Mercredi',
    JEUDI : 'Jeudi',
    VENDREDI : 'Vendredi',
    SAMEDI : 'Samedi',
    DIMANCHE : 'Dimanche',
    BREAKFAST_LABEL : 'Petit-déjeuner',
    BREAKFAST_VALUE : 'Breakfast',
    LUNCH_LABEL : 'Déjeuner', 
    LUNCH_VALUE : 'Lunch', 
    SNACK_LABEL : 'Collation',
    SNACK_VALUE : 'Snack',
    DINER_LABEL : 'Dîner',
    DINER_VALUE : 'Dinner',
    CONFIRM : 'Confirmer',
    CANCEL : 'Annuler',
    AJOUTER : 'Ajouter',
    HOMME : 'homme',
    HOMME_LABEL : 'Homme',
    FEMME : 'femme',
    FEMME_LABEL : 'Femme',
    SEDENTAIRE : 'sedentaire',
    SEDENTAIRE_LABEL : 'Sedentaire',
    EXERCICE_LEGER : 'exercice_leger',
    EXERCICE_LEGER_LABEL : 'Exercice léger',
    EXERCICE_MODERE : 'exercice_moderé',
    EXERCICE_MODERE_LABEL : 'Exercice modéré',
    EXERCICE_INTENSE : 'exercice_intense',
    EXERCICE_INTENSE_LABEL : 'Exercice intense',
    EXTRA_ACTIF : 'extra_actif',
    EXTRA_ACTIF_LABEL : 'extra_actif',
    PERTE_POIDS : 'perte_poids',
    GAIN_POIDS : 'gain_poids',
    SOUMETTRE : 'Soumettre',
    OUI : 'oui',
    NON : 'non',
}